In [1]:
import numpy as np

In [3]:
arr=np.array([10,20,30,40,50])
a=np.sum(arr)
print(a)

150


In [4]:
a=np.min(arr)
print(a)

10


In [11]:
a=np.max(arr)
print(a)

50


In [10]:
a=np.mean(arr)
print(a)

30.0


In [9]:
a=np.median(arr)
print(a)

30.0


In [14]:
arr=np.array([90,80,10,20,30,40,50])
a=np.argmin(arr)
print(a)

2


In [15]:
arr=np.array([90,80,10,20,30,40,50,100])
a=np.argmax(arr)
print(a)

7


In [20]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
a=np.sum(arr,axis=1)
print(a)

[[1 2 3 4]
 [5 6 7 8]]
[10 26]


In [19]:
arr=np.array([[1,2],[3,4]])
print(arr)
a=np.sum(arr,axis=0)
print(a)

[[1 2]
 [3 4]]
[4 6]


In [21]:
np.eye(3) # can create Rectangle Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [24]:
np.identity(3,4)  # can't create Rectangle Matrix

TypeError: Cannot interpret '4' as a data type

In [28]:
np.diag([10,20,30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [30]:
arr=np.array([[10,  1,  2],
       [ 0, 20,  0],
       [ 0,  0, 30]])
np.diag(arr)

array([10, 20, 30])

In [34]:
arr=np.array([10,20,30,40,50])
np.where(arr>20)

(array([2, 3, 4]),)

In [33]:
arr=np.array([10,20,30,40,50])
np.where(arr>20,"Greater","Lesser")

array(['Lesser', 'Lesser', 'Greater', 'Greater', 'Greater'], dtype='<U7')