In [2]:
import numpy as np

# Attribute - Additional Information 

- ndim [tells Arrays Dimension]
- dtype [ Element data type]
- shape [rows and Columns]
- size [total Element Count]
- itemsize [memory -taken -in bytes]
- nbytes [total memoery  occupied by Elements]
- T (Transpose) Row-> columnn vice versa
- strides (Bytes taken to jump from one element to another)
- flag 

In [14]:
a=np.array([1,2,3,4,5])
print(a.shape)
print(a.size)
print(a.dtype)
print(f"{a.itemsize} bytes")
print(f"{a.nbytes } bytes")

(5,)
5
int64
8 bytes
40


In [15]:
a=np.array([1,2,3,4,5],dtype=np.int8)
print(a.shape)
print(a.size)
print(a.dtype)
print(f"{a.itemsize} bytes")
print(f"{a.nbytes } bytes")

(5,)
5
int8
1 bytes
5 bytes


In [16]:
a=np.array([1,2,3,4,5],dtype=np.float32)
print(a.shape)
print(a.size)
print(a.dtype)
print(f"{a.itemsize} bytes")
print(f"{a.nbytes } bytes")

(5,)
5
float32
4 bytes
20 bytes


In [6]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.size)

(2, 3)
6


In [7]:
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.shape)
print(a.size)

(2, 2, 3)
12


In [22]:
a=np.array([[1,2,3,4,5,6],[6,5,4,3,2,1]])
print("Shape",a.shape)
b=a.T
print(b)
print("Shape",b.shape)

Shape (2, 6)
[[1 6]
 [2 5]
 [3 4]
 [4 3]
 [5 2]
 [6 1]]
Shape (6, 2)


In [ ]:
# strides

In [23]:
a=np.array([[1,2,3],[4,5,6]])
print("Bytes",a.itemsize)
print(a.strides)


Bytes 8
(24, 8)


In [24]:
a=np.array([[1,2,3],[4,5,6]],dtype=np.int8)
print("Bytes",a.itemsize)
print(a.strides)


Bytes 1
(3, 1)


In [26]:
arr=np.array([1,2,3])
print(arr.flags) # memory Properties

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [46]:
arr=np.array([1,2,3,4,5,6])
arr=np.shape=(3,3)
print(arr)

(3, 3)


In [32]:
arr=np.array([1,2,3,4,5,6])
arr=arr.reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [53]:
arr=np.array([1,2,3,4,5,6])
arr.reshape(2,3)
print(arr)

[1 2 3 4 5 6]


In [33]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a=a.reshape(4,2)
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a=a.reshape(2,4)
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [35]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a=a.reshape(8,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [41]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a.resize(5,4,refcheck=False)
print(a)

[[1 2 3 4]
 [5 6 7 8]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [42]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a.resize(1,3,refcheck=False)
print(a)

[[1 2 3]]


In [45]:
a=np.array([1,2,3,4,5])
print(a[1:3])

[2 3]


In [9]:
import numpy as np
a=[[1,2],[3,4]]
a=np.array(a)
print(a.flatten())
print(a)
a[0]=10
print(a)
print("--------------")
b=[[1,2],[3,4]]
b=np.array(b)
print(b.ravel())
b[0]=10
print(b)

[1 2 3 4]
[[1 2]
 [3 4]]
[[10 10]
 [ 3  4]]
--------------
[1 2 3 4]
[[10 10]
 [ 3  4]]
