# Array 
    collection of homogenous values Stored in  a single Variable 
    Stores Data in Same Type, so it is Very Faster,
    used for Mathematical operations.
    
    Type: 
        1D - Single Dimension # only Rows 
        2D - Two Dimension  # Rows and Columns 
        3D - Three Dimension # Base,Rows and Columns
        nD - Multi Dimension # Collection of 2D arrays


In [1]:
import numpy as np

In [7]:
a=[1,2,3,4] # 1d 
a= np.array(a)
print(a.ndim)
print(a)


1
[1 2 3 4]


In [6]:
a=np.array([[1,2],[3,4]])
a= np.array(a)
print(a.ndim)
print(a)

2
[[1 2]
 [3 4]]


In [5]:
a=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
a= np.array(a)
print(a.ndim)
print(a)

3
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [8]:
np.zeros(2)

array([0., 0.])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [5]:
np.zeros((2,2),int)

array([[0, 0],
       [0, 0]])

In [11]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((3,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [14]:
np.zeros((2,3,2,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [15]:
np.ones(2)

array([1., 1.])

In [2]:
np.ones(2,int)

array([1, 1])

In [7]:
np.ones(2,str)

array(['1', '1'], dtype='<U1')

In [3]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.full(6,8)

array([8, 8, 8, 8, 8, 8])

In [20]:
np.full((6,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [22]:
print(list(range(1,10,2)))
      

[1, 3, 5, 7, 9]


## arange(start,stop,step)

In [23]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## linspace(start,stop,no_of_values)

In [26]:
np.linspace(1,2,5) # Even Space

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [27]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [9]:
np.empty(6)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 3.11522054e-307,
       1.42413555e-306, 1.78019082e-306])

In [3]:
np.empty(6,dtype=np.int8)

array([ 44,  32,  39,  60, 105,  50], dtype=int8)

In [2]:
np.array([[1,2,3,4],[5,6,7]]

_IncompleteInputError: incomplete input (3517706952.py, line 1)