In [1]:
import numpy as np

# Indexing and Slicing

In [10]:
a=np.array(np.arange(5))
print(a)
print(a[2])
print(a[-2])

[0 1 2 3 4]
2
3


In [20]:
a=[[1,2],[3,4]]
print(a)
a=np.array(a)
print(a)
print(a.shape)
print(a.ndim)
print("Oth Row",a[0])
print("1st Row",a[1])
print(a[-1])
print(a[0][1])
print(a[1][0])
print(a[1,0])


[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
(2, 2)
2
Oth Row [1 2]
1st Row [3 4]
[3 4]
2
3
3


In [26]:
a=[[[1,2],[3,4]],[[5,6],[7,8]]]
print(a)
a=np.array(a)
print(a)
print(a.shape)
print(a.ndim)
print("0th row",a[0])
print("1st row",a[1])
print("---------------")
print(a[1,0,0])
print("---------------")
print(a[1,1])

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3
0th row [[1 2]
 [3 4]]
1st row [[5 6]
 [7 8]]
---------------
5
---------------
[7 8]


In [34]:
a=np.array(np.arange(5))
print(a)
print(a[1:4])
print(a[1:])
print(a[:4])
print(a[::-1])
print(a[::2])

[0 1 2 3 4]
[1 2 3]
[1 2 3 4]
[0 1 2 3]
[4 3 2 1 0]
[0 2 4]


In [40]:
a=np.array(
    [
        [10,20,30],
        [40,50,60],
        [70,80,90]
    ]
)
print(a)
print("----------")
print(a[0])
print("----------")
print(a[-1])
print("----------")
print(a[::-1])
print("----------")
print(a[:,::-1])
print("----------")
print(a[::-1,::-1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
----------
[10 20 30]
----------
[70 80 90]
----------
[[70 80 90]
 [40 50 60]
 [10 20 30]]
----------
[[30 20 10]
 [60 50 40]
 [90 80 70]]
----------
[[90 80 70]
 [60 50 40]
 [30 20 10]]
