# Numpy
##  NumPy stands for Numerical Python.
##  It is a Python library used for numerical and scientific computing.
##  It provides a powerful N-dimensional array (ndarray) object.
##  It is faster than Python lists because it is implemented in C.
##  It is widely used in Data Analytics, Data Science, Machine Learning, and AI.
##  It integrates well with libraries like Pandas, Matplotlib, and Scikit-learn.

# Features
- Fast compared to Python List 
- Mathematical  and array matrix 
- vectorization
- Higly Used in Data Analytics , Data science , AI/ML
- Less memory usage
- Random number generation
- Array reshaping and manipulation
- Broadcasting support
- Easy integration with other Python libraries


# Installation

pip install numpy

In [3]:
import numpy as np

In [2]:
a=[1,2,3,4]
print(type(a))

<class 'list'>


In [4]:
a=[1,2,3,4]
a=np.array(a)
print(type(a))

<class 'numpy.ndarray'>


#dataType 
- int8	8-bit integer	(-128 to 127)
- int16	16-bit integer	(eg:1000)
- int32	32-bit integer	(eg:50000)
- int64	64-bit integer	(Very large integers)
- uint8	Unsigned 8-bit integer	(0 to 255)
- float16	16-bit (3–4 decimal digits)	(3.14)
- float32	32-bit (7 decimal digits)	(2.5)
- float64	64-bit (15–16 decimal digits) (default)	(10.25)
- bool_	Boolean	(True, False)
- complex64	Complex number	2+3j
- complex128	High-precision complex	5+6j
- str_	String	"Apple"
- bytes_	Byte string	b"abc"
- object_	Python objects	List, Dict, Custom objects

# 8bit=1byte
## 2pow 8
-128,0,127


In [13]:
a=[1,2,3,1]
print(a)
a=np.array(a)
print(type(a))
print(a.dtype)

[1, 2, 3, 1]
<class 'numpy.ndarray'>
int64


In [14]:
a=[1.1,1.5]
print(type(a))
a=np.array(a)
print(a.dtype)

<class 'list'>
float64


In [15]:
a=['a','b']
print(type(a))
a=np.array(a)
print(a.dtype)

<class 'list'>
<U1


In [23]:
a=[10,20]
print(type(a))
a=np.array(a,dtype=np.int8)
print(a.dtype)

<class 'list'>
int8


In [22]:
a=[10,20]
print(type(a))
a=np.array(a,dtype=np.float16)
print(a.dtype)
print(a)

<class 'list'>
float16
[10. 20.]


In [7]:
a=[1.2,2.5,3.6,7.9]
a=np.array(a)
print(a.dtype)
b=a.astype(np.int8)
print(b)
print(b.dtype)

float64
[1 2 3 7]
int8


In [30]:
a=["true","false"]
a=np.array(a,dtype=np.bool_)
print(a.dtype)

bool


In [31]:
a=[-1,-2,-3]
a=np.array(a)
print(a.dtype)

int64


In [11]:
a=[1,2,3,4]
print(type(a))
a=np.array(a) 
print(type(a))
print(a.dtype)
a=a.astype(np.int8)
print(a.dtype)

<class 'list'>
<class 'numpy.ndarray'>
int64
int8


In [13]:
a=[129,12,34]
print(type(a))
a=np.array(a,dtype=np.int8) 
print(type(a))
print(a.dtype)

<class 'list'>


OverflowError: Python integer 129 out of bounds for int8

In [14]:
a=[-129,12,34]
print(type(a))
a=np.array(a,dtype=np.int8) 
print(type(a))
print(a.dtype)

<class 'list'>


OverflowError: Python integer -129 out of bounds for int8

In [17]:
a=[-129,12,34]
print(a)
print(type(a))
a=np.array(a) 
print(type(a))
print(a.dtype)
a=a.astype(np.int8) # 129 +256
print(a)
print(type(a))
print(a.dtype)

[-129, 12, 34]
<class 'list'>
<class 'numpy.ndarray'>
int64
[127  12  34]
<class 'numpy.ndarray'>
int8


In [18]:
a=[129,12,34]
print(a)
print(type(a))
a=np.array(a) 
print(type(a))
print(a.dtype)
a=a.astype(np.int8) # 129 -256
print(a)
print(type(a))
print(a.dtype)

[129, 12, 34]
<class 'list'>
<class 'numpy.ndarray'>
int64
[-127   12   34]
<class 'numpy.ndarray'>
int8


In [20]:
a=[1,2,3,4]
print("LIST ",a)
print("Array ",np.array(a))

LIST  [1, 2, 3, 4]
Array  [1 2 3 4]


In [25]:
a=[1,2,3,4]
print("LIST ",a)
a=np.array(a)
print("Array ",a)
print("Array ",a)

LIST  [1, 2, 3, 4]
Array  [1 2 3 4]
Array  [1 2 3 4]


In [24]:
a=[1,2,3,4]
print("LIST ",a)
print("Array ",np.array(a)) # it wont affect the original List
print("LIST ",a)

LIST  [1, 2, 3, 4]
Array  [1 2 3 4]
LIST  [1, 2, 3, 4]


In [27]:
a=[1,2.3,True,"Apple"]
print(a)
a=np.array(a)  # convert Everything to String
print(a)
print(a.dtype)

[1, 2.3, True, 'Apple']
['1' '2.3' 'True' 'Apple']
<U32


In [31]:
a=[True,False,"apple"]
print(a)
a=np.array(a)
print(a)
a=a.astype(np.bool_)
print(a)

[True, False, 'apple']
['True' 'False' 'apple']
[ True  True  True]


In [30]:
a=[True,False]
print(a)
a=np.array(a)
a=a.astype(np.bool_)
print(a)

[True, False]
[ True False]
