In [1]:
import numpy as np

In [3]:
a=[1,2,3,4]
b=[6,7,8,9]
print(a+b)
print(a*b)

[1, 2, 3, 4, 6, 7, 8, 9]


TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
print(a*3)
print(a+3)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


TypeError: can only concatenate list (not "int") to list

In [11]:
a=[1,2,3,4]
b=[6,7,8,9]
a=np.array(a)
b=np.array(b) 
print("Add",a+b)
print("subtract",a-b)
print("Multiply",a*b)
print("divide",a/b)
print("floor division",a//b)
print("modulus",a%b)
print("Exponential",a**2)

Add [ 7  9 11 13]
subtract [-5 -5 -5 -5]
Multiply [ 6 14 24 36]
divide [0.16666667 0.28571429 0.375      0.44444444]
floor division [0 0 0 0]
modulus [1 2 3 4]
Exponential [ 1  4  9 16]


In [15]:
a=[1,2,3,4]
b=[6,7,8,9]
a=np.array(a)
b=np.array(b) 
print("Add",np.add(a,b))
print("subtract",np.subtract(a,b))
print("Multiply",np.multiply(a,b))
print("divide",np.divide(a,b))
print("floor division",np.floor_divide(a,b))

Add [ 7  9 11 13]
subtract [-5 -5 -5 -5]
Multiply [ 6 14 24 36]
divide [0.16666667 0.28571429 0.375      0.44444444]
floor division [0 0 0 0]


In [19]:
a=[10,20,30,40,55]
a=np.array(a)
print(a*2) # broadcasting
print(a[a%2==0])
print(a%2)

[ 20  40  60  80 110]
[10 20 30 40]
[0 0 0 0 1]
