In [2]:
import numpy as np

In [11]:
a=np.array([["m1","m2"],['1','2'],['2','3'],['2','3']])
print(a.ndim)
np.savetxt("sample.csv",a,delimiter=',',fmt="%s")
#a = np.delete(a, 0, axis=0)
#np.savetxt("sample.csv",a,delimiter=',',fmt="%s")


2


In [18]:
a=[1,2,3,4]
b=[5,6,7,8]
print(a)
np.stack((a,b)) # default axis=0

[1, 2, 3, 4]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.stack((a,b),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.stack((a,b),axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [19]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])