In [1]:
import numpy as np

In [3]:
np.random.rand()

0.7111676614388087

In [4]:
np.random.rand(3)

array([0.12914918, 0.32364038, 0.00386347])

In [5]:
np.random.rand(2,3)

array([[0.84550095, 0.15513896, 0.03605839],
       [0.74791073, 0.11421565, 0.27588262]])

In [23]:
np.random.randint(1,10)

3

In [49]:
arr=np.array(["Apple","orange","Banana"])
np.random.choice(arr)

np.str_('Apple')

In [36]:
np.random.seed(21)
np.random.rand(3)

array([0.04872488, 0.28910966, 0.72096635])

In [38]:
rng=np.random.default_rng()
rng.random()

0.18801312320142316

In [39]:
rng.random()*10

2.8233525877024404

In [43]:
rng.integers((1,6))

array([0, 5])

In [51]:
rng.integers(1,6,size=5)

array([2, 4, 2, 2, 4])

In [54]:
arr=np.array(["Apple","orange","Banana"])
rng.choice(arr,size=5,replace=True)

array(['orange', 'Banana', 'Banana', 'Banana', 'Banana'], dtype='<U6')

In [55]:
arr=np.array(["Apple","orange","Banana"])
rng.choice(arr,size=5,replace=False)

ValueError: Cannot take a larger sample than population when replace is False

In [57]:
arr=np.array(["Apple","orange","Banana"])
rng.choice(arr,size=2,replace=False)

array(['Apple', 'orange'], dtype='<U6')